export const ORDER_CREATE_CART_ITEMS_REQUEST: 'ORDER_CREATE_CART_ITEMS_REQUEST' =
	'ORDER_CREATE_CART_ITEMS_REQUEST';
export const ORDER_CREATE_CART_ITEMS_SUCCESS: 'ORDER_CREATE_CART_ITEMS_SUCCESS' =
	'ORDER_CREATE_CART_ITEMS_SUCCESS';
export const ORDER_CREATE_CART_ITEMS_FAIL: 'ORDER_CREATE_CART_ITEMS_FAIL' =
	'ORDER_CREATE_CART_ITEMS_FAIL';

export const ORDERS_DETAILS_REQUEST: 'ORDERS_DETAILS_REQUEST' =
	'ORDERS_DETAILS_REQUEST';
export const ORDERS_DETAILS_SUCCESS: 'ORDERS_DETAILS_SUCCESS' =
	'ORDERS_DETAILS_SUCCESS';
export const ORDERS_DETAILS_FAIL: 'ORDERS_DETAILS_FAIL' = 'ORDERS_DETAILS_FAIL';
