export const ORDER_CREATE_CART_ITEMS_REQUEST_PENDING: 'ORDER_CREATE_CART_ITEMS_REQUEST_PENDING' =
	'ORDER_CREATE_CART_ITEMS_REQUEST_PENDING';
export const ORDER_CREATE_CART_ITEMS_REQUEST_SUCCESS: 'ORDER_CREATE_CART_ITEMS_REQUEST_SUCCESS' =
	'ORDER_CREATE_CART_ITEMS_REQUEST_SUCCESS';
export const ORDER_CREATE_CART_ITEMS_REQUEST_FAIL: 'ORDER_CREATE_CART_ITEMS_REQUEST_FAIL' =
	'ORDER_CREATE_CART_ITEMS_REQUEST_FAIL';

export const ORDER_DETAILS_REQUEST_PENDING: 'ORDER_DETAILS_REQUEST_PENDING' =
	'ORDER_DETAILS_REQUEST_PENDING';
export const ORDER_DETAILS_REQUEST_SUCCESS: 'ORDER_DETAILS_REQUEST_SUCCESS' =
	'ORDER_DETAILS_REQUEST_SUCCESS';
export const ORDER_DETAILS_REQUEST_FAIL: 'ORDER_DETAILS_REQUEST_FAIL' =
	'ORDER_DETAILS_REQUEST_FAIL';
export const ORDER_DETAILS_RESET: 'ORDER_DETAILS_RESET' = 'ORDER_DETAILS_RESET';

export const ORDER_PAY_REQUEST_PENDING: 'ORDER_PAY_REQUEST_PENDING' =
	'ORDER_PAY_REQUEST_PENDING';
export const ORDER_PAY_REQUEST_SUCCESS: 'ORDER_PAY_REQUEST_SUCCESS' =
	'ORDER_PAY_REQUEST_SUCCESS';
export const ORDER_PAY_REQUEST_FAIL: 'ORDER_PAY_REQUEST_FAIL' =
	'ORDER_PAY_REQUEST_FAIL';
export const ORDER_PAY_RESET: 'ORDER_PAY_RESET' = 'ORDER_PAY_RESET';

export const ORDERS_LIST_REQUEST_PENDING: 'ORDERS_LIST_REQUEST_PENDING' =
	'ORDERS_LIST_REQUEST_PENDING';
export const ORDERS_LIST_REQUEST_SUCCESS: 'ORDERS_LIST_REQUEST_SUCCESS' =
	'ORDERS_LIST_REQUEST_SUCCESS';
export const ORDERS_LIST_REQUEST_FAIL: 'ORDERS_LIST_REQUEST_FAIL' =
	'ORDERS_LIST_REQUEST_FAIL';
export const ORDERS_LIST_RESET: 'ORDERS_LIST_RESET' = 'ORDERS_LIST_RESET';
