export const PRODUCT_DETAILS_REQUEST_PENDING: 'PRODUCT_DETAILS_REQUEST_PENDING' =
	'PRODUCT_DETAILS_REQUEST_PENDING';
export const PRODUCT_DETAILS_REQUEST_SUCCESS: 'PRODUCT_DETAILS_REQUEST_SUCCESS' =
	'PRODUCT_DETAILS_REQUEST_SUCCESS';
	export const PRODUCT_DETAILS_REQUEST_FAIL: 'PRODUCT_DETAILS_REQUEST_FAIL' =
		'PRODUCT_DETAILS_REQUEST_FAIL';
		
		export const UPDATE_PRODUCT_DETAILS: 'UPDATE_PRODUCT_DETAILS' =
			'UPDATE_PRODUCT_DETAILS';
