export const PRODUCTS_LIST_REQUEST_PENDING: 'PRODUCTS_LIST_REQUEST_PENDING' =
	'PRODUCTS_LIST_REQUEST_PENDING';
export const PRODUCTS_LIST_REQUEST_SUCCESS: 'PRODUCTS_LIST_REQUEST_SUCCESS' =
	'PRODUCTS_LIST_REQUEST_SUCCESS';
export const PRODUCTS_LIST_REQUEST_FAIL: 'PRODUCTS_LIST_REQUEST_FAIL' =
	'PRODUCTS_LIST_REQUEST_FAIL';

export const DELETE_PRODUCT_FROM_LIST: 'DELETE_PRODUCT_FROM_LIST' =
	'DELETE_PRODUCT_FROM_LIST';
export const ADD_PRODUCT_TO_LIST: 'ADD_PRODUCT_TO_LIST' = 'ADD_PRODUCT_TO_LIST';
export const UPDATE_PRODUCT_IN_LIST: 'UPDATE_PRODUCT_IN_LIST' =
	'UPDATE_PRODUCT_IN_LIST';
