export const PRODUCTS_LIST_REQUEST_PENDING: 'PRODUCTS_LIST_REQUEST_PENDING' =
	'PRODUCTS_LIST_REQUEST_PENDING';
export const PRODUCTS_LIST_REQUEST_SUCCESS: 'PRODUCTS_LIST_REQUEST_SUCCESS' =
	'PRODUCTS_LIST_REQUEST_SUCCESS';
export const PRODUCTS_LIST_REQUEST_FAIL: 'PRODUCTS_LIST_REQUEST_FAIL' =
	'PRODUCTS_LIST_REQUEST_FAIL';
