export const USER_LOGIN_REQUEST_PENDING: 'USER_LOGIN_REQUEST_PENDING' =
	'USER_LOGIN_REQUEST_PENDING';
export const USER_LOGIN_REQUEST_SUCCESS: 'USER_LOGIN_REQUEST_SUCCESS' =
	'USER_LOGIN_REQUEST_SUCCESS';
export const USER_LOGIN_REQUEST_FAIL: 'USER_LOGIN_REQUEST_FAIL' =
	'USER_LOGIN_REQUEST_FAIL';

export const USER_REGISTER_REQUEST_PENDING: 'USER_REGISTER_REQUEST_PENDING' =
	'USER_REGISTER_REQUEST_PENDING';
export const USER_REGISTER_REQUEST_SUCCESS: 'USER_REGISTER_REQUEST_SUCCESS' =
	'USER_REGISTER_REQUEST_SUCCESS';
export const USER_REGISTER_REQUEST_FAIL: 'USER_REGISTER_REQUEST_FAIL' =
	'USER_REGISTER_REQUEST_FAIL';

export const USER_LOGOUT: 'USER_LOGOUT' = 'USER_LOGOUT';

export const USER_DETAILS_REQUEST_PENDING: 'USER_DETAILS_REQUEST_PENDING' =
	'USER_DETAILS_REQUEST_PENDING';
export const USER_DETAILS_REQUEST_SUCCESS: 'USER_DETAILS_REQUEST_SUCCESS' =
	'USER_DETAILS_REQUEST_SUCCESS';
export const USER_DETAILS_REQUEST_FAIL: 'USER_DETAILS_REQUEST_FAIL' =
	'USER_DETAILS_REQUEST_FAIL';

export const USER_UPDATE_PROFILE_REQUEST_PENDING: 'USER_UPDATE_PROFILE_REQUEST_PENDING' =
	'USER_UPDATE_PROFILE_REQUEST_PENDING';
export const USER_UPDATE_PROFILE_REQUEST_SUCCESS: 'USER_UPDATE_PROFILE_REQUEST_SUCCESS' =
	'USER_UPDATE_PROFILE_REQUEST_SUCCESS';
export const USER_UPDATE_PROFILE_REQUEST_FAIL: 'USER_UPDATE_PROFILE_REQUEST_FAIL' =
	'USER_UPDATE_PROFILE_REQUEST_FAIL';
export const USER_UPDATE_PROFILE_RESET: 'USER_UPDATE_PROFILE_RESET' =
	'USER_UPDATE_PROFILE_RESET';

export const ADMIN_USERS_LIST_REQUEST_PENDING: 'ADMIN_USERS_LIST_REQUEST_PENDING' =
	'ADMIN_USERS_LIST_REQUEST_PENDING';
export const ADMIN_USERS_LIST_REQUEST_SUCCESS: 'ADMIN_USERS_LIST_REQUEST_SUCCESS' =
	'ADMIN_USERS_LIST_REQUEST_SUCCESS';
export const ADMIN_USERS_LIST_REQUEST_FAIL: 'ADMIN_USERS_LIST_REQUEST_FAIL' =
	'ADMIN_USERS_LIST_REQUEST_FAIL';
export const ADMIN_USERS_LIST_RESET: 'ADMIN_USERS_LIST_RESET' =
	'ADMIN_USERS_LIST_RESET';
export const USER_IS_NOT_ADMIN: 'USER_IS_NOT_ADMIN' = 'USER_IS_NOT_ADMIN';

export const ADMIN_DELETE_USER_REQUEST_PENDING: 'ADMIN_DELETE_USER_REQUEST_PENDING' = 'ADMIN_DELETE_USER_REQUEST_PENDING';
export const ADMIN_DELETE_USER_REQUEST_SUCCESS: 'ADMIN_DELETE_USER_REQUEST_SUCCESS' = 'ADMIN_DELETE_USER_REQUEST_SUCCESS';
export const ADMIN_DELETE_USER_REQUEST_FAIL: 'ADMIN_DELETE_USER_REQUEST_FAIL' = 'ADMIN_DELETE_USER_REQUEST_FAIL' ;
